### ISSUE TITLE
Linux executable not working

### ISSUE THREAD

**Issue by cool-dev-guy** [Chukobyte/crescent#212]
gives the error:
```
[ERROR] Failed to create window!  SDL error: 'SDL not configured with OpenGL/GLX support'
[ERROR] Failed to initialize rendering!
[ERROR] Failed to initialize seika framework!
```

**Comment by Chukobyte** [comment]
@cool-dev-guy Thanks for reporting!  Which flavor and version of linux are you running?

**Comment by cool-dev-guy** [comment]
@Chukobyte linuxmint(ubuntu)

**Comment by Chukobyte** [comment]
Have you installed sdl2 with vcpkg or something else?

**Comment by cool-dev-guy** [comment]
> Have you installed sdl2 with vcpkg or something else?

@Chukobyte i have sdl2 on my system that i use for my other SDL2 projects.

**Comment by Chukobyte** [comment]
> > Have you installed sdl2 with vcpkg or something else?
> 
> @Chukobyte i have sdl2 on my system that i use for my other SDL2 projects. from `apt`.

Which version of SDL2 are you using?  Also you have you used OpenGL 3.3 on that same machine for other projects?  Trying to rule those problems out.

**Comment by Chukobyte** [comment]
Do you happen to have discord?  It will probably be easier to troubleshoot by chatting.

**Comment by cool-dev-guy** [comment]
yea i have a discord dc : cool_dev_guy

**Comment by Chukobyte** [comment]
Sent a request.  I've tried `cool_dev_guy` and `cool-dev-guy` but it didn't work, so I sent it to `cooldevguy`.  Hopefully that's you 😄!

**Comment by cool-dev-guy** [comment]
> Sent a request. I've tried `cool_dev_guy` and `cool-dev-guy` but it didn't work, so I sent it to `cooldevguy`. Hopefully that's you 😄!

@Chukobyte sorry man,my discord was `cool_guy_dev`(i guess i rearranged the words)

**Comment by Chukobyte** [comment]
Can revisit this, but we'll need to be able to repro
